export enum StatusRegistration {
  APROVADO = 'APROVADO',
  EM_VALIDACAO = 'EM_VALIDACAO',
  PENDENTE_ENVIO = 'PENDENTE_ENVIO',
  PENDENTE_VALIDACAO = 'PENDENTE_VALIDACAO',
  REPROVADO = 'REPROVADO',
}
